POST http://localhost:3000/api/auth/signup

{
    "name" : "mail trap",
    "email" : "mailtrap2@gmail.com",
    "password" : "1234",
    "id" : 2    
} 

###
POST http://localhost:3000/api/auth/login

{
    "email" : "lol@gmail.com",
    "password" : "1234"
} 

###
POST http://localhost:3000/api/auth/verify-otp

{
    "otp" : "350369"
}